import React from "react";
import "./Styling/ConnectUs.css"
export default function ConnectUsData() {
  return (
    <>
    <div className="dash-head">
                Connect Us
            </div>
      <table>
        <tr>
          <th>Sr.no.</th>
          <th>E-mail</th>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>1</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>2</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
        <tr>
          <td>3</td>
          <td>gauravnarnaware3112003@gmail.com</td>
        </tr>
      </table>
    </>
  );
}
